### ISSUE TITLE
Increase node size for faster builds

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/mybinder.org-deploy#1068]
Our current node sizes were determined when the maximum number of pods per node enforced by GKE / Kubernetes was 100. However, [this is no longer the case](https://cloud.google.com/sdk/gcloud/reference/container/node-pools/create#--max-pods-per-node). 

In our use case, I think larger nodes make sense. The primary advantage would be faster launches, since more pods will land up on nodes where the image already exists. The primary disadvantage would be that autoscaling's 'minimum unit' now becomes larger, so the cost analysis is goin to be different. I *think* it should be ok though.

My vague intuition is to increase node size by 50%, and increase max number of pods the same, and see what happens.

**Comment by betatim** [comment]
I think this is a good idea.

We seem to go from ~6 to ~4 nodes as the max and min which would fit with making nodes 50% bigger and auto-scaling by one unit instead of two.

From https://grafana.mybinder.org/d/nDQPwi7mk/node-activity?refresh=1m&panelId=26&fullscreen&orgId=1&var-cluster=prometheus we have about ~70 user pods per node so the new max limit per node should be around 140-150 (some head room for none user pods).

@choldgraf the last node pool upgrade was done by @sgibson91, do you want to take this opportunity to exercise your GKE foo?

related: https://github.com/jupyterhub/team-compass/issues/180

**Comment by choldgraf** [comment]
it feels like right now the problems w/ speed are more of an issue than being more incremental in our cost savings, so I'd be +1 on this I think

**Comment by betatim** [comment]
Trying:
```sh
gcloud beta --project=binder-prod container node-pools create $new_pool \
    --cluster=prod-a \
    --zone=us-central1-a \
    --disk-type=pd-ssd \
    --disk-size=1000 \
    --machine-type=n1-highmem-8 \
    --num-nodes=2 \
    --local-ssd-count=1 \
    --enable-autoscaling \
    --enable-autorepair \
    --min-nodes=1 \
    --max-nodes=8 \
    --node-labels hub.jupyter.org/node-purpose=user,mybinder.org/pool-type=users
    --max-pods-per-node=150
```
gives an error message that you can't go above 110. So I think this just let's you set the maximum to a value below 110.

**Comment by choldgraf** [comment]
also just a follow up that they state their pod/node quotas here:

https://cloud.google.com/kubernetes-engine/quotas

**Comment by yuvipanda** [comment]
Ah, boo :'( Thanks for actually testing this out rather than just reading docs, @betatim! 

I'm going to close this now as something we can't quite do.

**Comment by betatim** [comment]
It was a good idea (we should ponder alternatives to achieve the same goal) and I could swear that I read a blog post by GKE where they said that you could now set the limit to a value above 110.

**Comment by minrk** [comment]
Another way that we could increase build performance is to have a build pool of dedicated (or prioritized) nodes.

**Comment by minrk** [comment]
I've also been thinking that there could be some use of `--cache-from` that could improve performance. In particular, if we published 'empty' images for common buildpack routes (e.g. build a repo with no config with each buildpack and pass that to `--cache-from`), we could potentially get much better cache performance and layer sharing between images. I'm not sure how these optimizations would behave in terms of the complexity vs performance trade-offs.

**Comment by betatim** [comment]
#1071 is related to the idea of dedicated build nodes.

Anecdotally (ie when I pay attention) all layers before "copy the repo contents" are "cached layers" on mybinder.org. It is very rare that I see them not being cached, especially if you exclude the times where repo2docker had changed and it was the first build (on that node) with the new `Dockerfile`.

Do you think we could use `--cache-from` for popular combinations of packages as well? My feeling is that the best we could hope to cover with the "empty images for caching" approach is to cover all steps up to the "now copy the repo contents".

I am excited about https://github.com/jupyter/repo2docker/pull/718 (and the hopefully much more straightforward PRs to do the same for `requirements.txt` and `environment.yml`) as a way to speed up rebuilds of a repository. Though it needs a higher chance of a given build to land on the same build node for the cache to be there.

**Comment by minrk** [comment]
> Do you think we could use --cache-from for popular combinations of packages as well?

Based on your anecdote, this shouldn't result in any significant improvement, so probably not worth our time. It would allow us to get more coverage when there are a few common starting points (e.g. Python 2.7, R buildpack) that need to get repopulated once for each node. It really is only the first build for a given shared configuration that has to do this, though.

> Do you think we could use --cache-from for popular combinations of packages as well?

Not really. Only for truly identical environment specifications, not *equivalent* environment specifications. This is basically what your PR  jupyter/repo2docker#718  does for R and mine in jupyter/repo2docker#410 does for conda and pip. It really saves single-repo rebuilds, but is highly unlikely to be shared across repos exactly, I would guess.

> My feeling is that the best we could hope to cover with the "empty images for caching" approach is to cover all steps up to the "now copy the repo contents".

Yes, absolutely. This is as far as we could hope to get. I feel like I see the initial conda install relatively often, but your anecdotal experience suggests otherwise.

**Comment by betatim** [comment]
> Yes, absolutely. This is as far as we could hope to get. I feel like I see the initial conda install relatively often, but your anecdotal experience suggests otherwise.

Maybe we should open an issue in repo2docker for this? As it would definitely help out local users of r2d who are unlikely to have a gigantic stack of layers in their cache.
