### ISSUE TITLE
Using Binder Hub to Teach Data Science

### ISSUE THREAD

**Issue by mafreitas** [jupyterhub/mybinder.org-deploy#1123]
I run a small data science club with the goal of introducing biomedical scientists to R and Python.  I have found that Jupyter notebooks are the best instructional aid for the club.  The biggest challenge I have faced is providing everyone access to the exact same environment with little setup.  When I ran across MyBinder.org I though this would be an excellent platform for experiential learning in R and Python.  To avoid running afoul of usage restrictions I wanted to see if a 1-2 x week class of 20-30 individuals using the site simultaneously would fall under acceptable use.  Thanks and keep up the great work.

**Comment by betatim** [comment]
Yes that is absolutely fine. It is one of the reasons mybinder.org exists :) Classes of 20-30 people hardly register on our stats, once you go beyond 50 simultaneous users we tend to notice. The limit we enforce is 100 concurrent users per repository, if you were constantly running into that we'd probably stop by your repository to find out what is going on. If you do other stuff we consider weird we will stop by your repo and open an issue to discuss (if we can't find a place to do that and as a last resort we would probably heavily throttle/ban your repo as a way to attract attention so that you come to us and we can talk :D)

As with all shared resources we'd appreciate if you could be a good citizen by:
* keeping your list of dependencies "minimal" (don't blindly dump all of the PyData ecosystem into your `environment.yml`, include only what you need)
* not adding massive data sets to your images
* not constantly rebuilding your repo just because you can

If you follow these points you will not only help keep mybinder.org running smoothly but also your repositories will start more quickly (shipping huge images around takes longer than shipping smaller ones :) ).

In general [the forum](https://discourse.jupyter.org/) is a better place for support and general chat things (most of the team and more hang out there as well). We try and keep the issue trackers of our repositories for topics related to changing stuff in the actual repository. This helps manage the tidal wave of notifications everyone receives.

Happy data science'ing and mention us to your friends ;)
