### ISSUE TITLE
Federation redirector - versions check

### ISSUE THREAD

**Issue by bitnik** [jupyterhub/mybinder.org-deploy#1188]
Hi, in September team meeting we were discussing about how to keep binder instances in sync. And one idea was

> if a member of the federation is “too far behind” we automatically stop sending traffic

For now this is a case only for GESIS Binder because we do the upgrades through our own repo and sometimes they are delayed.

So first questions is do we want to add versions check into federation redirector? If yes, I would like to do that. I think can start with a PR "if an instance doesn't have the same versions as mybinder.org, remove it from list of healthy binders". What do you think?

**Comment by betatim** [comment]
Sounds like a good plan to me. Like you suggested I would check the version(s) of the tools on https://gke.mybinder.org/versions (this should be marked as "prime" in the redirector so we don't have to hard code it) and then mark every other host that doesn't have these exact versions as "unhealthy'.

**Comment by manics** [comment]
As a long-term goal it might be nice to allow other binderhubs to be upgraded to newer minor versions (so backwards compatible according to semver), before the main binderhub is upgraded. This would allow full capacity to be maintained.

**Comment by choldgraf** [comment]
Since the major/minor versions etc don't mean a ton in BinderHub, what if we also included the date in the `/versions` endpoint? So it'd serve up something like:

```
{
 "builder": "jupyter/repo2docker:0.10.0-100.g0dba611",
 "builder_date": "2019-02-02",
 "binderhub": "0.1.0+406.ga168d06.dirty",
 "binderhub_date": "2019-08-01"
}
```

In https://github.com/jupyterhub/binderhub/pull/863/files I couldn't figure out how to send a request to the GitHub API to figure out the date because requests were blocked, but if the dates were in there it'd be trivial to figure out "how many days is XXX BinderHub behind the master BinderHub".
