### ISSUE TITLE
Henchbot upgrade for new helm chart tags

### ISSUE THREAD

**Issue by betatim** [jupyterhub/mybinder.org-deploy#1328]
@henchbot and @henchc I think we need to fix up the bot again because the format of the tags has changed for the binderhub helm chart

https://jupyterhub.github.io/helm-chart/#development-releases-binderhub

has two examples of the most recent tag format. There are extra letters infront of the numbers now.

---

Is there a way for us to see the output of the bot and help fix it?

**Comment by bitnik** [comment]
This is the fix (and also improvement for parsing old and new chart versions) I did for our bot: https://github.com/gesiscss/orc/compare/796c870c6879f49df48b876f2b04b7eb0aef103d...9bd788049b67ee3858222bb65f8cf76e47777e49

**Comment by consideRatio** [comment]
Nice @bitnik !! I noted an outdated example in the inline code, outdated considering what chartpress now would generate, but not outdated with regards to what may be found in a helm chart repo as that is from alö past versions of chartpress also.

chartpress will now always prefix with n and h on the number of commits since tag, and the git hash.

**Comment by henchc** [comment]
Thanks, all! I will take a closer look tonight and update it.

**Comment by henchc** [comment]
Ok, we should be back and business, although in a sleepy stupor I managed to completely destroy the repo so I had to restore it :/ . But it should be reconnected to heroku and running correctly now :)

**Comment by consideRatio** [comment]
Thank you a lot @henchbot for your work on this! :heart: :tada:

**Comment by choldgraf** [comment]
@henchc thanks so much!
