### ISSUE TITLE
Upgrading GKE k8s version

### ISSUE THREAD

**Issue by betatim** [jupyterhub/mybinder.org-deploy#1458]
I will try and upgrade the k8s version of the GKE cluster tomorrow morning.

Posting here in case someone wants to join or do it themselves to gain experience. https://mybinder-sre.readthedocs.io/en/latest/index.html is the guide to follow.

**Comment by consideRatio** [comment]
Nice! :tada:

Hey btw, a feature on GKE that have been [added not that long ago is node surge](https://cloud.google.com/kubernetes-engine/docs/concepts/cluster-upgrades#surge), that means that during an upgrade they add one additional node by default before others are shut down to be upgraded. That can help prevent issues where pods fail to relocate because there isn't enough free resources etc.

Will you try upgrade to k8s 1.16? It was the latest minor version of k8s I saw on GKE recently for their normal users that isn't part of a fast release channel that have access to even more recent version ahead of others. I'm curious to know if it works!

Feel free to ping me on WhatsUp if you want an additional set of eyes on something! :heart:

**Comment by betatim** [comment]
We are on 1.14 so the highest we can upgrade to in one step today is 1.15.11-gke.13.

Upgrading staging right now.

**Comment by betatim** [comment]
Staging is upgraded, prod has a new node pool on 1.15.11

**Comment by betatim** [comment]
All user nodes in the old pool are now cordoned, waiting for them to drain.
