### ISSUE TITLE
Increase limit for SciPy tutorial (Bayesian) to 300

### ISSUE THREAD

**Issue by hugobowne** [jupyterhub/mybinder.org-deploy#1476]
### 1. Who you are

Hugo Bowne-Anderson (Coiled) and Eric Ma (Novartis) @ericmjl 

### 2. A few details about the event/course/context

SciPy conference

### 3. If money is changing hands (attendees pay a fee, speaker is getting paid, free, etc)

Registration:  $75/$25US for students

Speakers paid $1KUS in total for material development time, is my understanding.

### 4. A link to the repository you are using

https://github.com/ericmjl/bayesian-stats-modelling-tutorial

### 5. What type of event it is:
- [ ] talk
- [x] workshop
- [ ] lecture course
- [ ] training session

out of curiosity, what's the difference between a workshop and a training session?

### 6. How many people you expect to attend the event

It's not clear to me. My understanding is that anybody who registered for SciPy _can_ attend. And there may be 900-1K registrants? 

### 7. The exact times and dates of the event(s) (with timezone information)

9am CDT Monday 07/06

### 8. How do you plan to give mybinder.org a shout out at the event

Not by getting 100s of people to launch binders and then talking for 10 minutes ;)

More seriously, by doing what i do every time: continually communicating that Binder is the go-to PyData stack & Jupyter way of spinning up labs // notebooks in executable & reproducible environments at the click of a button // badge.

**Comment by manics** [comment]
How did it go? There was a minor deployment hiccup but hopefully that didn't affect your workshop.

**Comment by ericmjl** [comment]
Thanks for pinging back, @manics! 

We still had some issues, but I'm not sure if they were related to capacity or something else. The main issue that I saw was that launching into a Binder session took a long time for some participants. This is something I've noticed even without conference-related capacity requests. Some had to launch into a Private Browsing window in order to access the session. (Same happened for me.)
