### ISSUE TITLE
Config option to disable jitsi video chat button?

### ISSUE THREAD

**Issue by seibert** [jupyterhub/mybinder.org-deploy#1562]
We recently noticed the "Join this repo's Video Chat" button appear on our Binder notebooks, and we are wondering if there is a way to opt-out of the button.  Built-in video chat is an interesting idea, but we're a little concerned that the possibility of user confusion (or even abuse) outweighs the utility, at least for our repository.  (If our repo was tied to a scheduled event, I think video chat could be pretty nice.)

I don't find anything in the docs about Jitsi, so I'm not sure if we have any control over it.

**Comment by betatim** [comment]
Having the Jitsi button in the UI is an experimental feature that we added "because we could and thought it would be useful". Since then we have been waiting for feedback. This is one of the first feedbacks :D so thanks for engaging!

There is currently no way for a repository to opt-out of having the button. How to make it so that a repo can opt-out would be interesting to look at. We inject the button at the level of the UI template for jupyter notebook. I'm wondering if a repo could come with its own template and via that suppress the button.

We tried to use defaults that minimise the potential for abuse (you don't auto join, camera off, sound off) but of course these are easy to switch if you want to be evil. What is the situation where you worry about abuse and what form would it take?

**Comment by mattwthompson** [comment]
I second the feedback above and would benefit from an opt-out config. It's a nice feature, but the UI implies to me something of a guarantee that the maintainers of a project will be on call for video chats.  My specific concern is that a user thinks the button "join this repo's Video chat" is a resource for feedback/troubleshooting, but it points to a room that's unlikely to have anybody in it. Perhaps renaming the button with slightly different phrasing could align it with the intention above (i.e. an experimental feature that could be useful to some but comes with no guarantees). I'm less concerned about getting zoombombed, since the links are hard to accidentally come across, if even accessible by malicious actors.

**Comment by betatim** [comment]
Do you have suggestion for how to label the button to remove the implied "click here to get support"? Maybe something in the direction of "chat to other users"?

I'd rather remove the button completely than make it configurable. The latter would bring a lot of complexity with it that IMHO isn't worth it.

**Comment by nannau** [comment]
A big +1 for allowing a config to turn the button off from me.

I am part of an organization developing curriculum using MyBinder for students to learn Python. We _really_ love MyBinder and after trying several ways of delivering curriculum, it outshines all of them and is a great learning tool. It does exactly what we need. 

However, given our intended audience, and that our MyBinders are public, the video conferencing option is a major concern since we don't want to accidentally provide students an external unmoderated video conference room.

**Comment by choldgraf** [comment]
I'm +1 on removing the button and providing documentation for how users can enable it through `postBuild` configuration etc...

**Comment by betatim** [comment]
There is a PR up to remove the button. I think it isn't worth making it configurable (this would require a whole new feature of having a config file in the repo), so the PR removes it for all repos.
