### ISSUE TITLE
403 cross-origin errors when pointing to a specific markdown file

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/mybinder.org-deploy#1638]
I found that if you directly try to point to a markdown in mybinder.org via `tree/path/to/file.md` then it raises a 403 error. E.g.:

![image](https://user-images.githubusercontent.com/1839645/94085355-b6c0f780-fdbc-11ea-9cf9-24687854c03d.png)

to reproduce the above:

http://mybinder.org/v2/gh/binder-examples/conda_environment/master?urlpath=tree/README.md

note that this does not happen if the `urlpath` points to an `ipynb` file (and you can also manually trigger this bug by putting `tree/README.md` in the URL in the browser)

anybody else run into this issue before? Is it new?

**Comment by manics** [comment]
This happens with jupyter-notebook:
```
docker run -it --rm -p 8888:8888 jupyter/base-notebook
```
Create a file `test.md`
http://127.0.0.1:8888/files/test.md gives a 403

**Comment by choldgraf** [comment]
Ah so this is not a Binder error per-se, but just the way that the notebook server works?

(note that it works fine in JupyterLab so maybe this is just one of those 'will be fixed when we switch the default to jupyterlab' things?)

**Comment by minrk** [comment]
It's a frustrating requirement of some XSSI issues (cross-site inclusion) that direct-links to files can't work, which is annoying. Notebooks work because they are loaded in a 'viewer' page, but what will be redirects to *raw* files like this won't. I'm a little surprised it happens in this case, since I thought we opened up CORS on mybinder.org, so there might be something we can fix for this one.

**Comment by minrk** [comment]
It's a bug in the notebook server that `allow_origin=*` isn't properly applied to these requests (https://github.com/jupyter/notebook/pull/5898) but we can work around it (https://github.com/jupyterhub/binderhub/pull/1226)
