### ISSUE TITLE
kubelet Garbage Collection

### ISSUE THREAD

**Issue by bitnik** [jupyterhub/mybinder.org-deploy#1652]
Hey! I just saw https://github.com/jupyterhub/binderhub/pull/1158 and remembered that ~4 months ago we disabled the image cleaner of BinderHub at GESIS and started to use the internal garbage collector of kubernetes (https://kubernetes.io/docs/concepts/cluster-administration/kubelet-garbage-collection/) which deletes the least recently used images when disk usage reaches to 85% until decreased to 80%. And so far we did't experience any problem or at least we are not aware of.

I thought maybe you find this useful and would like to try it out. We could disable the image cleaner or increase `imageGCThresholdHigh` to 90 and check how it works

https://github.com/jupyterhub/mybinder.org-deploy/blob/c9d1a87cf537d85e1a7c78c1e3cda286e0fc1fc0/mybinder/values.yaml#L170-L177

**Comment by bitnik** [comment]
Ah I just realized that image cleaner is already disabled on host. So I guess this means that mybinder.org already uses the internal one? I think I am confused about how image cleaner works, please close the issue if it doesnt make sense.

**Comment by betatim** [comment]
I think this is what we do on (most) mybinder.org clusters: we use docker-in-docker to build images for repositories and those are stored in a separate place from the images used by the dockerd that kubernetes Pods use/run in.

This means the k8s internal GC can't clean up user images, because they are in a different directory. So we have two locations that need garbage collecting. One is taken care of by the kubelet, for the other we use the image cleaner.

The kubelet GC looks at how full the whole disk is to figure out if it needs to clean up or not. Our image cleaner does the same. So they used to get in each others way/be super confused that the disk was (too) full and that deleting images wouldn't result in more space. The reason for this is that the "other" image cache was using up space. The result was that often both image GCs just deleted all images which lead to bad performance.

The solution is to have two partitions. One for the kubelet controlled images and one for the DIND controlled images. We use the builtin GC for the kubelet controlled ones and our own image cleaner for the DIND controlled ones.

There is an exception, on OVH we don't have a second partition so we run the image cleaner for the DIND images in a mode where it looks at the total size of the images directory and makes a decision based on that. Figuring out the actual size is much slower and the limits need some finetuning so using two partitions when you use DIND is best.

**Comment by bitnik** [comment]
Thanks a lot Tim for the explanation! and sorry for the confusion, you just refreshed my head :)

I am closing this issue.
