### ISSUE TITLE
Fix lint and validate workflow

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/mybinder.org-deploy#1672]
Our helm lint and validate workflow is having issues after some upgrades to the chart and migrating to helm3

**Comment by minrk** [comment]
I think this may have had to do more with making a PR from a branch of this repo instead of a fork, since it looks to be passing on both new PRs and master. Maybe need to check our logic for what happens when a PR is issued from within the repo. Errors looked like it *expected* the secrets to be unlocked, but the unlock step didn't happen. So maybe our conditions aren't consistent between those two steps.

**Comment by sgibson91** [comment]
I'm not sure. [This run](https://github.com/jupyterhub/mybinder.org-deploy/actions/runs/331113119) came from a branch within the repo so it was correct to unlock the secrets with git-crypt, there was just something wrong with the charts at that particular moment. And actually this `error calling required: Proxy token must be a 32 byte random string generated with 'openssl rand -hex 32'!` is the problem I was facing when migrating Hub23 to helm3 and ended up deleting and redeploying from scratch.

**Comment by sgibson91** [comment]
For clarity: I encountered this exact same error at this stage of the migration even though I had a local, plaintext values file with unencrypted secrets in it.
