### ISSUE TITLE
Upgrading OVH cluster

### ISSUE THREAD

**Issue by minrk** [jupyterhub/mybinder.org-deploy#1791]
the OVH cluster is running a quite old version (1.15) and is starting to be a source of challenges (https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1994). What is the process of upgrading the kubernetes version in the OVH cluster (@mael-le-gal)?

It's possible that upgrading the cluster could fix #1786 .

**Comment by mael-le-gal** [comment]
Indeed the binder cluster is still on 1.15 however I remember that I once tried to upgrade it to 1.16 and the helm charts of binder where not ready for it and it broke.

If you tell me that it's ok I can upgrade it. What will be the expected version ? I think we currently support 1.19

**Comment by mael-le-gal** [comment]
The problem was the following : https://github.com/jupyterhub/binderhub/issues/1116

**Comment by betatim** [comment]
Should we just try and see what happens if you upgrade to k8s 1.19? On GKE we are running on 1.17.14-gke.400 without any problems, unsure if anyone has tried running on a newer version. I think for JupyterCon a BinderHub was deployed on OVH infrastructure, maybe if we can locate the people who did that we can get some knowledge from them.

**Comment by MridulS** [comment]
We are on k8s 1.19 at GESIS. Everything seems running without any issues.

**Comment by mael-le-gal** [comment]
Ok then, I'll do the upgrade of the k8s today

**Comment by mael-le-gal** [comment]
Kubernetes upgraded to version `1.17.16`

**Comment by betatim** [comment]
Closing this now as the upgrade is done and we have another issue for "always pull".
