### ISSUE TITLE
Proposition to change the cert-manager certificate issuer type

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/mybinder.org-deploy#1827]
### What?

I'd like to change the [kind of our certificate issuer](https://github.com/jupyterhub/mybinder.org-deploy/blob/387451935f370d0f5c6c20ef14852add77e56275/mybinder/templates/cluster-issuer.yaml#L3) from `ClusterIssuer` to `Issuer`

### The Difference

As far as I understand, a cluster issuer will find certificates for any annotated ingresses across the entire cluster, whereas an issuer can be configured just to monitor annotated ingresses in a given k8s namespace.

### Why?

I'd like to deploy Hub23 (Turing's private BinderHub) onto the same cluster as the Turing federation to save running costs (both economically and in person hours). Since Hub23 has very few users I don't think this will impact the federation deployment at all. But the current issuer has the Binder team's google group email as a contact, and I'd like to provide an issuer with my own contact to prevent noise in that group. Having an issuer per deployment namespace appears to be the cleanest way to achieve this?

### Alternatives?

Have a missed a k8s/cert-manager trick while thinking about this? (I admit, it's been a bit of a back-of-the-brain problem while other stuff has been going on!)

**Comment by minrk** [comment]
I think this is quite reasonable.

I do believe it's overrideable even with a default clusterIssuer, because you can set the annotation:

```yaml
cert-manager.io/issuer: my-issuer-name
```

[on your ingress resources](https://cert-manager.io/docs/usage/ingress/#supported-annotations).

So the difference is:

If we keep the default clusterIssuer, you must:

- create an Issuer in your namespace, with any name
- set the `cert-manager.io/issuer: my-issuer-name` annotation on each of your ingress resources

If we switch to defaultIssuer instead of defaultClusterIssuer, the above will still work without any changes, but you can *also*:

- create an issuer named exactly `letsencrypt-prod`
- no need to set  `cert-manager.io/issuer` if you create the default issuer, but no harm either

**Comment by sgibson91** [comment]
Thanks for the tips! I think I like the first option as it's the least meddlesome for now, and I also want to make sure that upgrading hub23 doesn't mess with the cert-manager namespace and mybinder.org certs

**Comment by minrk** [comment]
👍

I think something that's been hard to get used to is that cert-manager is really intended to be a "per cluster" thing, not a "per chart/app/etc." thing. They kinda sorta try to make it work that way, but as we have learned it is quite fraught and often just doesn't work, and isn't the project's intended use.

So picking a configuration of cert-manager that works for all cluster tenants (if more than one) makes good sense. In that respect, if you expect to have multiple deployments, using defaultIssuer seems like a good practice because then what's part of the deployment is the letsencrypt Issuer configuration. So there's still something *required* to configure per namespace (the Issuer), but not cert-manager itself.

I think a good way to choose between ClusterIssuer and Issuer for the default is: who should be considered to "own" the certs? The "cluster operator" (@sgibson91)  or each individual app (mybinder.org team, hub23 team, etc.), which will depend on how "multi-tenant" the cluster really is. I think both can make sense, and with the annotations above, it's always possible to do different things with each deployment.

But with mybinder.org, since these are mostly single-purpose clusters, the difference between defaultIssuer and defaultClusterIssuer doesn't come up much.

**Comment by sgibson91** [comment]
@minrk can I get a review on https://github.com/alan-turing-institute/hub23-deploy/pull/342 please? (Merging it won't deploy anything yet)
