### ISSUE TITLE
Clean up built images with prefixes that aren't the current prefix

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/mybinder.org-deploy#189]
since they'll never be used again.

They cause problems leading to the 'no space left on disk' error

**Comment by minrk** [comment]
Writing some notes here, for lack of a better place right now. This should go in an incident/debugging place

1. I saw "no space left on device"
2. @yuvipanda pointed out that logs are aggregated in [stack driver](https://console.cloud.google.com/logs/viewer?project=binder-prod&minLogLevel=0&expandAll=false&timestamp=2017-11-30T18:52:24.000000000Z&resource=container%2Fcluster_name%2Fprod-a&filters=text:%22no%20space%20left%20on%20device%22), so I did a search there for "no space left on device"
3. that turned up the messages, which identify their instance_id (this is not their name!)

    <img width="768" alt="screen shot 2017-11-30 at 19 57 14" src="https://user-images.githubusercontent.com/151929/33449337-c1dc5f3a-d608-11e7-916a-c356c5bedfab.png">

4. filtering out other messages from the same instance id showed that this one was the primary culprit and it was not a widespread issue:

   <img width="413" alt="screen shot 2017-11-30 at 20 07 14" src="https://user-images.githubusercontent.com/151929/33449847-4f320974-d60a-11e7-83b3-40ce162fc487.png">

5. I found a mapping of instance name to id with (there's a better way, right?):

    ```bash
    for instance in `gcloud compute instances list | grep gke | awk '{print $1}'`; do
      echo $instance;
      gcloud compute instances describe $instance --format json | jq .id;
   done
   ```
6. that identified the primary instance as `gke-prod-a-default-pool-6ab3d8ec-rp9h`
7. @yuvipanda pointed out that this out of space error seems to be caused by too many docker layers, *not* actual disk usage.
8. further, since we have updated the build prefix recently, there are lots of images with earlier prefixes that we can be sure won't be used.
9. So I logged in to the node (`gcloud compute ssh gke-prod-a-default-pool-6ab3d8ec-rp9h`) and started deleting old images:

   ```bash
   # repeated for a few old image prefixes
   docker rmi $(docker images | grep 'gcr.io/binder-prod/r2d-3cd4519' | awk '{print $1":"$2}')
   docker rmi $(docker images -f "dangling=true" -q)
   ```

  This deleted hundreds of images. If this was the issue, it should stop the error message from occurring.
10. wait...watch logs
11. The error message came a few more times from the same node of the next few minutes, suggesting that maybe the issue was not fixed.
12. Give up on intervention and `kubectl cordon gke-prod-a-default-pool-6ab3d8ec-rp9h` the node so  it doesn't get any new containers.

**Comment by yuvipanda** [comment]
Note that this intervention has worked for me every time before. Not sure why not this time.

**Comment by minrk** [comment]
It's possible that I just didn't wait long enough and the logs I saw were delayed.

**Comment by minrk** [comment]
If we leave the node in, we can uncordon it when we are are at less peak traffic and see what's up

**Comment by minrk** [comment]
Follow-up from some investigation today: I realized that my node-identification is wrong. The instance id in the logs is always the binderhub node, since that's where the log comes from. The error presumably (I'm not 100% sure) occurs on the node running the build whose logs fail to be watched.

It's been challenging to identify the node where the failure occurs because it's not in the log message, nor is the pod name, only the pod UUID (metadata.uid). Since pods are deleted, it's hard to find the right one after the fact.

I've recently identified the currently difficult node as `*-jsv7`, probably not coincidentally our oldest node (25d).

Some diagnostic output:

This shows that jsv7 has a high (not highest!) image layer count:

```bash
for instance in $(gcloud compute instances list | grep gke | awk '{print $1}'); do
  echo $instance
  gcloud compute ssh $instance -- docker images -a | wc -l
done

gke-prod-a-default-pool-6ab3d8ec-jsv7
    1477
gke-prod-a-default-pool-6ab3d8ec-mhw8
     471
gke-prod-a-default-pool-6ab3d8ec-mzfb
    1468
gke-prod-a-default-pool-6ab3d8ec-rq6b
    1796
gke-prod-a-default-pool-6ab3d8ec-xq51
    1378
```

However, looking at *mounts* (~all of which are docker overlay mounts):

```bash
for instance in $(gcloud compute instances list | grep gke | awk '{print $1}'); do
  echo $instance
  gcloud compute ssh $instance -- mount | wc -l
done

gke-prod-a-default-pool-6ab3d8ec-jsv7
    3328
gke-prod-a-default-pool-6ab3d8ec-mhw8
     759
gke-prod-a-default-pool-6ab3d8ec-mzfb
    2577
gke-prod-a-default-pool-6ab3d8ec-rq6b
     609
gke-prod-a-default-pool-6ab3d8ec-xq51
     572
```

The bad node has an outlier number of mounts. This suggests to me that it's actually mounts that are more directly relevant and not just images, and that `mzfb` will be the next one to have this problem. It also happens to be our second oldest node (at 19d). Interestingly, there doesn't seem to be a strong correlation of image count and mount count. So perhaps there's something where docker is failing to unmount layers?

Folks on kubernetes slack pointed me to `df -i` as inode exhaustion might be the culprit, but it doesn't appear to be:

```bash
$ df -i
Filesystem       Inodes   IUsed    IFree IUse% Mounted on
/dev/root         79360   13004    66356   17% /
devtmpfs        7731435     288  7731147    1% /dev
tmpfs           7731651       1  7731650    1% /dev/shm
tmpfs           7731651    1284  7730367    1% /run
tmpfs           7731651      16  7731635    1% /sys/fs/cgroup
tmpfs           7731651       1  7731650    1% /mnt/disks
tmpfs           7731651      13  7731638    1% /tmp
/dev/sda8          4096      11     4085    1% /usr/share/oem
/dev/sda1      65010720 8450237 56560483   13% /mnt/stateful_partition
tmpfs           7731651      45  7731606    1% /var/lib/cloud
overlayfs       7731651      67  7731584    1% /etc
```

**Comment by minrk** [comment]
Figured out we can get the actual logs better by looking directly at the [VM logs](https://console.cloud.google.com/logs/viewer?project=binder-prod&minLogLevel=0&expandAll=false&resource=gce_instance&filters=text:%22no%20space%20left%22), which makes it much easier to identify the bad node.

Strangely, the latest errors aren't showing the node, perhaps because the problem has broken log forwarding. There have been no VM logs captured in gcloud from the affected node in 3 days. But the last logs from the node on Dec 2 do include this "no space on device" message. The last message to arrive from this node was: [exit status 1](https://console.cloud.google.com/logs/viewer?project=binder-prod&minLogLevel=0&expandAll=true&timestamp=2017-12-05T13%3A33%3A54.478404000Z&resource=gce_instance%2Finstance_id%2F4874803091664833146&advancedFilter=resource.type%3D%22gce_instance%22%0Aresource.labels.instance_id%3D%224874803091664833146%22%0Aresource.labels.zone%3D%22us-central1-a%22%0Aresource.labels.project_id%3D%22binder-prod%22%0Atimestamp%3D%222017-12-02T13%3A58%3A20.000000000Z%22%0AinsertId%3D%22qnd4eog2ajnvdz%22) from kubelet before the logs went dark. The node continued to function, but at diminished health, and with no logs reporting.


I found the actual logs with `journalctl` after sshing to the bad node:

```bash
$ sudo journalctl | grep -i "no space left" | head -n 10
Dec 03 13:46:26 gke-prod-a-default-pool-6ab3d8ec-jsv7 kubelet[1565]: W1203 13:46:26.965691    1565 raw.go:87] Error while processing event ("/sys/fs/cgroup/cpuset/kubepods/besteffort/pod5bd07ab6-d830-11e7-aa1e-42010a80001e": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/cpuset/kubepods/besteffort/pod5bd07ab6-d830-11e7-aa1e-42010a80001e: no space left on device
Dec 03 13:46:26 gke-prod-a-default-pool-6ab3d8ec-jsv7 kubelet[1565]: W1203 13:46:26.966560    1565 raw.go:87] Error while processing event ("/sys/fs/cgroup/memory/kubepods/besteffort/pod5bd07ab6-d830-11e7-aa1e-42010a80001e": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/memory/kubepods/besteffort/pod5bd07ab6-d830-11e7-aa1e-42010a80001e: no space left on device
Dec 03 13:46:26 gke-prod-a-default-pool-6ab3d8ec-jsv7 kubelet[1565]: W1203 13:46:26.966830    1565 raw.go:87] Error while processing event ("/sys/fs/cgroup/cpu,cpuacct/kubepods/besteffort/pod5bd07ab6-d830-11e7-aa1e-42010a80001e": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/cpu,cpuacct/kubepods/besteffort/pod5bd07ab6-d830-11e7-aa1e-42010a80001e: no space left on device
Dec 03 13:46:26 gke-prod-a-default-pool-6ab3d8ec-jsv7 kubelet[1565]: W1203 13:46:26.967624    1565 raw.go:87] Error while processing event ("/sys/fs/cgroup/blkio/kubepods/besteffort/pod5bd07ab6-d830-11e7-aa1e-42010a80001e": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/blkio/kubepods/besteffort/pod5bd07ab6-d830-11e7-aa1e-42010a80001e: no space left on device
Dec 03 13:46:27 gke-prod-a-default-pool-6ab3d8ec-jsv7 kubelet[1565]: W1203 13:46:27.101040    1565 raw.go:87] Error while processing event ("/sys/fs/cgroup/cpu,cpuacct/system.slice/run-r5e4bc7059f6a4bf5b7288bc0ee1f2049.scope": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/cpu,cpuacct/system.slice/run-r5e4bc7059f6a4bf5b7288bc0ee1f2049.scope: no space left on device
Dec 03 13:46:27 gke-prod-a-default-pool-6ab3d8ec-jsv7 kubelet[1565]: W1203 13:46:27.101137    1565 raw.go:87] Error while processing event ("/sys/fs/cgroup/blkio/system.slice/run-r5e4bc7059f6a4bf5b7288bc0ee1f2049.scope": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/blkio/system.slice/run-r5e4bc7059f6a4bf5b7288bc0ee1f2049.scope: no space left on device
Dec 03 13:46:27 gke-prod-a-default-pool-6ab3d8ec-jsv7 kubelet[1565]: W1203 13:46:27.101337    1565 raw.go:87] Error while processing event ("/sys/fs/cgroup/memory/system.slice/run-r5e4bc7059f6a4bf5b7288bc0ee1f2049.scope": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/memory/system.slice/run-r5e4bc7059f6a4bf5b7288bc0ee1f2049.scope: no space left on device
Dec 03 13:46:27 gke-prod-a-default-pool-6ab3d8ec-jsv7 kubelet[1565]: W1203 13:46:27.110915    1565 raw.go:87] Error while processing event ("/sys/fs/cgroup/cpu,cpuacct/system.slice/var-lib-docker-overlay2-779a6ebae39b92349061c7945ae042718430326dde63293a13ce1df7364aed8b-merged.mount": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/cpu,cpuacct/system.slice/var-lib-docker-overlay2-779a6ebae39b92349061c7945ae042718430326dde63293a13ce1df7364aed8b-merged.mount: no space left on device
Dec 03 13:46:27 gke-prod-a-default-pool-6ab3d8ec-jsv7 kubelet[1565]: W1203 13:46:27.111001    1565 raw.go:87] Error while processing event ("/sys/fs/cgroup/blkio/system.slice/var-lib-docker-overlay2-779a6ebae39b92349061c7945ae042718430326dde63293a13ce1df7364aed8b-merged.mount": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/blkio/system.slice/var-lib-docker-overlay2-779a6ebae39b92349061c7945ae042718430326dde63293a13ce1df7364aed8b-merged.mount: no space left on device
Dec 03 13:46:27 gke-prod-a-default-pool-6ab3d8ec-jsv7 kubelet[1565]: W1203 13:46:27.111152    1565 raw.go:87] Error while processing event ("/sys/fs/cgroup/memory/system.slice/var-lib-docker-overlay2-779a6ebae39b92349061c7945ae042718430326dde63293a13ce1df7364aed8b-merged.mount": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/memory/system.slice/var-lib-docker-overlay2-779a6ebae39b92349061c7945ae042718430326dde63293a13ce1df7364aed8b-merged.mount: no space left on device
```

which point me to https://github.com/moby/moby/issues/29638 and https://github.com/google/cadvisor/issues/1581 . Neither seems to point to a solution other than rebooting the node. It seems in general that there's something docker isn't cleaning up about itself.

There does seem to be a leak suggesting that we should be deleting nodes once they are at least ~7 days old.

I've cordoned the bad node (`-jsv7`) and will delete it once it has drained. I think we should perhaps preemptively cordon node `-mzfb`, which looks like it will be the next to go.

**Comment by minrk** [comment]
I went ahead and cordoned `mzfb` preemptively, since it is likely to be the next one to exhibit the problem. We could also leave it uncordoned and see what happens. I don't know if we want to keep `jsv7` around to keep attempting to diagnose what went wrong, or just delete it.

**Comment by minrk** [comment]
I used [this notebook](https://gist.github.com/minrk/e91a1169cd399d71a357264fc204d3e5) to poke around about this stuff.

**Comment by willingc** [comment]
@minrk Great detective work and beautiful notebook. 

It seems like this goes back to  11-26-17. Is there an easy way to grab the logs +/- 2 min of this timestamp for the particular node (`-jsv7`)?

<img width="759" alt="screenshot 2017-12-06 at 7 19 32 am" src="https://user-images.githubusercontent.com/2680980/33663495-d9fdf97e-da55-11e7-9017-364179aa92c3.png">

**Comment by yuvipanda** [comment]
Closing since this has been sorted out in other ways.

I opened https://github.com/jupyterhub/mybinder.org-deploy/issues/800 for a related issue.
