### ISSUE TITLE
Review dependabot configuration

### ISSUE THREAD

**Issue by manics** [jupyterhub/mybinder.org-deploy#1919]
In https://github.com/jupyterhub/mybinder.org-deploy/pull/1914 I pinned all docs dependencies to fix a build issue.

I also added a dependabot configuration file
https://github.com/jupyterhub/mybinder.org-deploy/blob/64e809a927e2baa4bde64cb464bc766319c6f0f1/.github/dependabot.yaml#L1-L6
to auto-update the dependencies.

However it looks like some dependabot PRs were opened even without the configuration file prior to my PR:
https://github.com/jupyterhub/mybinder.org-deploy/issues?q=label%3Adependencies+is%3Aclosed

Was this configured outside the repo? Should we remove the dependabot file I added and hope everything just works, or add the hidden config back in?

**Comment by consideRatio** [comment]
@manics hmmm not sure why those were showing up unless they were security patches - dependabot can submit PRs or similar if it detects security issues I think.

I would say we go for what we have, an explicit dependabot configuration in this repo, and then don't think about it ;D The configuration we have looks good to me. I prefer to put things on monday night so I do all kinds of automation bumps weekly but at the same week of the day as well instead of having a sprinkle of notifications across the week.

I'll go ahead and close this as I see no action point worth taking. If i observe an explanation to the previous dependabot PRs, I'll follow up here.
