### ISSUE TITLE
Unsure if I would need a resource bump

### ISSUE THREAD

**Issue by wallynovak** [jupyterhub/mybinder.org-deploy#1936]
### 5. What type of event it is:
- [ ] talk
- [X] workshop
- [ ] lecture course
- [ ] training session

### 8. How do you plan to give mybinder.org a shout out at the event - I specifically talk about the benefits of mybinder.org for teaching and plan to have users fork the repository so that they have it to edit themselves for future teaching. Sorry I am just submitting this I am actually somewhat new to binder.org itself. My questions are 1 - is it better to ask for this increase (say to 200 people for 2.5 hours) or is it better to have them fork the repository and run it themselves in mybinder.org. I was planning on the latter as this would result in fewer than 100 people in a single repository and removes one barrier for faculty actually editing and using this repository to teach in the future.

Thank you!
Wally

**Comment by choldgraf** [comment]
Hey there - so there is a 100 session limit for repositories, so you needing a limit will depend on what % of the attendees you expect to actually be there and run their own Binder sessions. In my experience, something like 40-50% often actually run Binders, so that might be fine for you. As far as forking repositories, it will definitely slow things down in general since everybody will have to build their own (and this itself might put a tax on mybinder.org), but might be a good way to teach others how to use Binder itself if you want to spend more time covering the Binder workflow

**Comment by manics** [comment]
Hopefully your workshop went well!
