### ISSUE TITLE
AGU cluster usage and shout out

### ISSUE THREAD

**Issue by betatim** [jupyterhub/mybinder.org-deploy#217]
https://mybinder.org/v2/gh/tylere/agu2017/master?urlpath=lab via @tylere there will be a mention of this at the [AGU](https://fallmeeting.agu.org/2017/) 10-15 December. Estimate 100-150 people maybe.

We should keep an eye out on the utilisation of the cluster. Maybe also post the command(s) here to grow/shrink it.

**Comment by yuvipanda** [comment]
Just increasing the size of the cluster manually won't work, since the autoscaler will just then resize it back down to the minimum size in the autoscaler. So the real way to do this is to set the minimum size of the autoscaler to the size you want. But that has the additional problem of a few minutes outage when the change propagates, which we do not want. It also costs more money to us.

Long term, we should do something like https://github.com/berkeley-dsep-infra/data8xhub/issues/7 in our autoscaler.

**Comment by betatim** [comment]
What will we do then?

**Comment by yuvipanda** [comment]
Ah, for now we should just increase the 'minimum cluster size' in autoscaler settings. It'll be a several minute k8s cluster outage, so we should do this when usage is lower

**Comment by yuvipanda** [comment]
This happened without incident! We didn't manually increase cluster size, but our autoscaler was good enough to do this without any manual intervention! So we're good to go depending on the autoscaler for future events like these too!

Thanks for showing us off, @tylere! Can you tell us how the reception was?

**Comment by yuvipanda** [comment]
Going to close this now. Let us know what we can do to help, @tylere!
