### ISSUE TITLE
A gap of analytics data due to downtime of processing raw data

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/mybinder.org-deploy#2394]
The analytics-publisher was down due to #2392 between 2022-10-20 - 11:00 and onwards until 2022-10-30 - (now, 15:50 UTC time)

![image](https://user-images.githubusercontent.com/3837114/198888290-c4802e0b-7ad6-40ae-a144-ac24b6c06638.png)

- [So now we miss processed events here](https://console.cloud.google.com/storage/browser/binder-events-archive;tab=objects?forceOnBucketsSortingFiltering=false&authuser=2&project=binderhub-288415&prefix=&forceOnObjectsSortingFiltering=true&pageState=(%22StorageObjectListTable%22:(%22s%22:%5B(%22i%22:%22displayName%22,%22s%22:%221%22)%5D)))
- [And have unprocessed raw events here](https://console.cloud.google.com/storage/browser/binder-events-raw-export/binderhub-events-text/2022/10?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&authuser=2&project=binderhub-288415&prefix=&forceOnObjectsSortingFiltering=false)

It would be possible to process this retroactively I assume, but I don't know much about the setup and won't do it myself.

**Comment by minrk** [comment]
I've fixed the events archive for 10/20-10/30, but there's a bigger issue that's more pressing. We haven't actually recorded any events from the primary cluster since the same time (still to today). These are not recoverable, since they are lost everywhere, so our events archive is just missing ~80-90% of events for the last month.

**Comment by minrk** [comment]
It turns out the logs _are_ there for GKE, but they are somehow not persisted tot he log sink. So we've only truly lost ~3 days of GKE events due to our 30 day retention. I've increased retention to 60 days to give us some time to figure it out

**Comment by minrk** [comment]
running a dump of the logs with:

```
gcloud alpha logging copy _Default storage.googleapis.com/binder-events-debug-2022-11 --location=global --log-filter='resource.type="k8s_container" AND logName="projects/binderhub-288415/logs/binderhub-events-text" AND timestamp < "2022-11-23T11:34:00Z"' --project=binderhub-288415
```

in a temporary bucket (`binder-events-debug-2022-11`). This should only include missing events (I can deduplicate any overlapping events at the end of that, if needed). It seems to take a really long time.

When I make sure that includes only the desired data, I'll copy it to the events archive with `gsutil rsync` and re-run events-archive collection for 2022/10/20 - 2022/11/23, which should pick up the new events automatically, since they'll be in the same format and folders, just with a new file suffix, so no collisions.

**Comment by minrk** [comment]
export and re-import finished.

Before:

<img width="942" alt="Screenshot 2022-11-23 at 15 32 31" src="https://user-images.githubusercontent.com/151929/203579785-ebab74a4-8a20-4b17-b806-335655d1af25.png">

After:

<img width="1130" alt="Screenshot 2022-11-23 at 16 04 25" src="https://user-images.githubusercontent.com/151929/203579804-9633152f-c714-4145-a436-db25fefda3bb.png">

Actually data for ~3 days total (mid 2022-10-20 - mid 2022-20-24) due to log retention.
