### ISSUE TITLE
Request for User Limit Increase for Lunar Science Workshop

### ISSUE THREAD

**Issue by MattEMoran** [jupyterhub/mybinder.org-deploy#2677]
### Who you are

I am the Software Team Lead for GLEE, a research project that is run through the University of Colorado, Boulder and NASA Colorado Space Grant Consortium. 

Link to Project Website: https://www.glee2023.org/ 

Link to Space Grant Website: https://www.colorado.edu/center/spacegrant/ 

### About the event

GLEE is currently hosting a self-guided, asynchronous remote workshop for student teams around the world where we are introducing them to the capabilities of LunaSats (custom microcontroller boards with onboard sensors) and their potential for lunar science use cases. We currently are providing resources and code through Google Classroom and the Arduino platform.  

We are adding an additional module to the workshop where student teams can use a series of Jupyter notebooks dubbed the LunaSat Power and Data Model (LPDM) to determine the power and data usage of different LunaSat sensor configurations. Mybinder.org is ideal for allowing teams to access these notebooks without worrying about the local installation process. 

### Any money changing hands?

There is no money changing hands.

### Repository link

https://github.com/GLEE2023/LPDM/tree/tim

### Type of event

workshop

### Number of attendees

1000

### Dates and times

July 5 at 8 AM MST - August 18 at 11:59 PM MST

### More than 2 weeks before event

Yes

### How you will support Binder

We will be introducing mybinder.org and Jupyter notebooks as new tools for workshop participants to use, as they are currently only familiar with the Arduino platform. A video explaining how to access and use the LPDM via mybinder.org will be available on YouTube. The launch of the LPDM will be given a shoutout on the GLEE Instagram. 

Instagram: @gleemission 

YouTube: @GLEE-2023 

### Extra information

There are about 2000 students currently participating in the workshop. Since student teams are spread out across many timezones, we’d anticipate 1000 as the highest number of users accessing the LPDM at any given time. Realistically, we feel this number may be closer to 500 if 1 student is accessing the LPDM on behalf of their team. 

Although the workshop has been ongoing, we are planning on launching the LPDM workshop module on July 5 at 8 AM MST. The workshop will end on August 18 at 11:59 PM MST. 

Thank you for your time! 

Sincerely, 
Matt

**Comment by manics** [comment]
Hi! Unfortunately mybinder.org has limited capacity at the moment due to a reduction in funding:
https://blog.jupyter.org/mybinder-org-reducing-capacity-c93ccfc6413f

Longer term we're working on getting more capacity.

It might be worth looking at JupyterLite, which is a WASM/WebAssembly version of JupyterLab that runs entirely in the browser and can be hosted on a static website such as GitHub pages:
https://jupyterlite.readthedocs.io/en/latest/

It's not identical to standard JupyterLab/Python, and you'll need to follow the JupyterLite docs to install your dependencies (pure python dependencies, and those which are compiled for WASM, should work), but it might be worth trying?

**Comment by MattEMoran** [comment]
Thank you for the quick response! I'll definitely look into JupyterLite.

**Comment by rgaiacs** [comment]
I'm closing this because the event already happen.
