### ISSUE TITLE
High School science workshop at Vanderbilt for https://github.com/rkunnawa/ssmv_eic

### ISSUE THREAD

**Issue by rkunnawa** [jupyterhub/mybinder.org-deploy#2681]
Hi Folks, 

Next week tuesday - friday, I will be running a high school workshop for 30 students with many others facilitating and other groups simultaneously working on this binder. I would like to request to set it up so that many users can access it without issue and also that it not take a long time to load - basically have it loaded once and for everyone to access. thanks!  

Cheers
Raghav

**Comment by manics** [comment]
Hi! Unfortunately mybinder.org has limited capacity at the moment due to a reduction in funding:
https://blog.jupyter.org/mybinder-org-reducing-capacity-c93ccfc6413f

30 users is within the default quota for each repository,  but at the moment we can't guarantee there'll be enough compute resources available. If you can setup an alternative JupyterHub/BinderHub as a backup that'd be advisable.

**Comment by rkunnawa** [comment]
Thanks Simon. I understand the issues with the funding and it’s certainly unfortunate. I will setup a few binders so that each group of students are comfortable in running it. 

Cheers
Raghav 


**************************************
First Name - Raghav 
Last Name - Kunnawalkam Elayavalli
Pronouns - they/them
email - ***@***.*** 
website - https://www.raghavke.me 

RHIC/AGS UEC member
Assistant Professor of Physics
Stevenson Center 6410
Physics & Astronomy Department
Vanderbilt University 
Nashville, TN 37235-1807
**************************************

**Comment by rgaiacs** [comment]
I'm closing this given the high school event already happen.
