### ISSUE TITLE
Incident report 2018-01-18

### ISSUE THREAD

**Issue by betatim** [jupyterhub/mybinder.org-deploy#291]
[Incident report](https://hackmd.io/OwRgnKBGCskLQgMwBZl2dZAmOAOAZtInAKYCGAbAAyRa0i7QAmQA?edit#) of the reddit hugofdeath. (this is mostly a note to myself to create a PR from the hackmd)

**Comment by yuvipanda** [comment]
w00t, thanks!

I think the core issues were two:

1. Culler not working for some reason
2. One node had a borked network connectivity to other nodes (but not the internet), probably due to https://status.cloud.google.com/incident/cloud-networking/18003. This caused all spawned pods to land on the 'least loaded node', except the 'least loaded node' was borked, so always continued to be least loaded. This was what caused the outage.

Additional action items:

1. Run the py.tests constantly and actively alert us when they fail (active monitoring)

**Comment by yuvipanda** [comment]
And thank you all very much for responding and writing this up, @betatim / @willingc!
