### ISSUE TITLE
Check if binder is still running 

### ISSUE THREAD

**Issue by navoshta** [jupyterhub/mybinder.org-deploy#448]
_This has been previously discussed in jupyterhub/binderhub#287._

[Juno app](https://itunes.apple.com/app/juno-jupyter-notebook-client/id1315744137) is caching any URL it receives from mybinder.org to avoid requesting extra instanced and to reduce load. As discussed previously, the decision was to simply try accessing the URL and checking if it returns 404 (i.e. it was destroyed) or 200 (i.e. still running). 

> As to seeing if a given user instance is still running, you could also make an API request to the notebook URL you got back. It should 404 if it is dead.

There are plans to introduce a redirect to mybinder.org for destroyed binders, therefore any binder URL will always return 200. Unfortunately, this would trick Juno into thinking every URL is in fact OK and it will never request a new URL for a repo.

While said redirect was in place, I managed to check few things, and it seems I could try using `…/api/status` instead, which wasn’t redirected and returned 404 for timed out binders. Is it something we should use in next Juno release? When are you planning to bring this redirect back?

**Comment by yuvipanda** [comment]
This has been temporarily 'fixed' in #446 and #447, since other projects relying on the API might also rely on this 404 response.

**Comment by yuvipanda** [comment]
@navoshta can you verify if your app is back to working?

**Comment by navoshta** [comment]
@yuvipanda Yes, it's working now. Thanks! Are there plans to bring the redirect back?

**Comment by minrk** [comment]
@navoshta yes, I think you should be using `/api/status`, as discussed in  jupyterhub/binderhub#287. That wouldn't have seen this issue. The redirect-to-200 was for 'likely human' requests (GETs to non-API urls). I think we can avoid restoring the 200 redirect, but I would recommend updating the URL to check anyway.

I think ultimately the dead-pod URL should serve a human-readable page, and the status should probably be 404. It was a 200 as a temporary fix because I didn't want to spend the time to get the patch serving a human-readable error page while we were dealing with an outage, so I redirected to a known page.

For humans, I think the current situation is worse than it was earlier (jupyterhub 403) and during this time (working but inexplicable binder landing page), but a good error page is the right thing to do in the long run, and I'll work on that. I think we can live with nginx 404 for a short period.

**Comment by minrk** [comment]
#461 introduces a more permanent 404 page, so I think you can safely assume that it won't go back to 200. Prior to yesterday, I believe the result was a 403 on `/hub/login` after redirects.

**Comment by navoshta** [comment]
Awesome, thanks @minrk! 

> I think you should be using /api/status, as discussed in jupyterhub/binderhub#287. That wouldn't have seen this issue. The redirect-to-200 was for 'likely human' requests (GETs to non-API urls).

Yes I found your suggestion in that thread and realised I probably should've used `.../api/status` instead.

> #461 introduces a more permanent 404 page, so I think you can safely assume that it won't go back to 200. Prior to yesterday, I believe the result was a 403 on /hub/login after redirects.

Good to know, however as advised I will update the URL to `.../api/status` just in case. I'm going to do that in the next minor release though, sparing us from an urgent patch release meanwhile.

Thanks for looking into that!
