### ISSUE TITLE
Implement per repo limits

### ISSUE THREAD

**Issue by betatim** [jupyterhub/mybinder.org-deploy#628]
Should we up the per repo limit for ipython/ipython-in-depth? We quite frequently run up against the 100 instances limit for this repo.

Currently we set the per repo limit globally. I don't think we should up the global limit but maybe for some repos (like the jupyter demo repos) we want a higher limit?

**Comment by choldgraf** [comment]
ehhh, I'm +0 on this...maybe for these we can just because they're Jupyter repos, though on the other hand I think they're not the *kind* of repo we want dominating on Binder (which ideally would be user repositories etc). Though I do agree a per-repo quota would be great.

**Comment by choldgraf** [comment]
also, I just got charged $180 in interest on my credit card because I didn't have enough $$$ in the bank to pay it due to the Binder charges, so in general I have a preference for not growing Binder usage too much until we can find out a payment solution that doesn't involve my personal finances :-(

**Comment by willingc** [comment]
I'm wondering if we could have a NumFocus account instead of Chris' for the monthly bill??

**Comment by choldgraf** [comment]
this would make Chris happy

**Comment by yuvipanda** [comment]
We have this now.
