### ISSUE TITLE
Consider putting all try.jupyter.org repositories on preemptible nodes

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/mybinder.org-deploy#687]
I was just chatting with @betatim about this, and I think @consideRatio has mentioned something like this before as well.

What if we put all of the `try.jupyter.org` binder instances on a separate preemptible nodepool. These are all generally short sessions, and they generate like 50% of the traffic to Binder. If we use preemptible nodes for this traffic, we'd reduce our costs by quite a bit. It'd also be a good way to get a feel for how disruptive the preemptible nodes are to users.

Anyone have thoughts on that?

**Comment by betatim** [comment]
Was thinking we could use https://github.com/jupyterhub/kubespawner/blob/472a66253a3a3e0c4f07c65830feef9a273d3ec4/kubespawner/spawner.py#L568 to check if the pod name matches a pattern and then assign a different node selector to the pod. The node pool with preemptible instances would have a different label from the one we currently use for "normal" user pods.

**Comment by minrk** [comment]
I love the idea of doing this.

The only technical question is how do we express the preference of node-pool based on the input (i.e. does binderhub specify a node pool in the request to jupyterhub, or does jupyterhub do the image:node lookup). It's doable either way.

Unfortunately, not all of the try.jupyter links point to dedicated repos. e.g. the main one is actually the ipython-in-depth tutorial (This should really be a dedicated "welcome to jupyter" repo, but it still isn't). So maybe the right source of info is the Referer header, so we only relegate links that are actually from try.jupyter.org?

If we're just doing it as an experiment to see if we can switch all of Binder over, then I think the repo is a good enough proxy for that info, and should be simpler to implement than Referer, I think.

**Comment by betatim** [comment]
I would try this in the cheapest possible way right now. In the long term we probably want some sophisticated way of doing this  but right now for mybinder.org I'd put the priority on getting some experience with using preemptible nodes and how much that annoys users.

If I had to choose I'd give a higher priority to having a way to signal to a user that they are about to be preempted/get feedback about the user experience over making the selection mechanism smarter.

Then we see what to do next once we know if pre-emptible nodes are or are not in the future of mybinder.org.

**Comment by yuvipanda** [comment]
I was talking to @jacobtomlinson about this at the Pangeo developer meeting. Pre-emptible instances (similar to spot instances on AWS) have a few drawbacks:

1. They always die after 24h, which means every day some number of users who are active at that time will get their service actively disrupted.
2. When there's a flux of new google cloud customers in the region / zone we're in, these disruptions will happen *more* frequently. For @jjacobtomlinson's case, I think they hit a pathological case due to brexit (!) and had issues getting any spot instances for a while.

From https://cloud.google.com/compute/docs/instances/preemptible,

> If your applications are fault-tolerant and can withstand possible instance preemptions, then preemptible instances can reduce your Compute Engine costs significantly. 

IMO, user pods are *not* fault tolerant, since them dying unexpectadly has a bad effect on users' experience. So I'd recommend *not* using pre-emptible instances for anything right now unless we are stretched for money (I'm not sure if we are)

**Comment by consideRatio** [comment]
@yuvipanda I've considered the issue with 24 hours, one could try to avoid old nodes with some custom logic i figure, but nothing is out there to support this with existing configuration on the scheduler.

If a user dies on a JH (perhaps not binder), it can be detrimental to when the user attempts to login again unless the hub has restarted in between. It is because the pod is left there in EVICTED state, not getting cleaned up, and the hub/kubespawner is clueless.

For a detailed report about an eviction event after a pod died on a preemptible instance on GKE, with a quite fresh helm chart at 0.7-hash
https://github.com/jupyterhub/kubespawner/issues/223

**Comment by choldgraf** [comment]
Have we ran the numbers for how much this would actually save us in monthly costs? I feel like that'd be helpful in determining whether it's worth it. We could configure things so that nodes with < 1 hour of time remaining before they're clobbered are cordoned or something like this.

**Comment by jacobtomlinson** [comment]
To follow on from what @yuvipanda mentioned we purposefully put notebook pods on regular instances and use spot instances for ephemeral pods like dask workers.

**Comment by yuvipanda** [comment]
@choldgraf the problem is we have no control over cordoning - the nodes will just disappear, and can do so at any moment of time. IMO notebook pods should never be on pre-emptible nodes, since it guarantees that some % of users *will* get their service disrupted every single day. If we wanna cut costs, #691 is a much better way to do so.

**Comment by betatim** [comment]
I think the focus of this issue should be coming up with a plan on how to gather feedback on how disruptive using these instances would be.

Picking a group of users who we think have a low probability of finding this annoying together with a notebook extension that saves notebooks to user's local storage should give us a chance to experiment with this. Then we will have some data and experience to further discuss what to do.

A local storage extension is a bit of work to write but it would be a useful feature for all binder users as a lot of people already experience the culling due to inactivity/timeouts. Which means it is effort well invested, even if we decide not to use preemptible instances after this experiment.

**Comment by yuvipanda** [comment]
@betatim my problem is that culling is based on user inactivity, while preemption is not. It means we might have users who get kicked out 1s after they get on. From a user perspective, this is indistinguishable from 'binder is broken'. To me, this makes it a general non-starter. 

If we can actually control when we cordon off nodes and what not, then it is acceptable. However, pre-emptive nodes do not let you do that, so IMO we shouldn't.

**Comment by yuvipanda** [comment]
Can this be closed now?

**Comment by choldgraf** [comment]
It sounds like here the answer is, "we should not do this because it'd be too disruptive to users" right?
