### ISSUE TITLE
allow outgoing ssh connections?

### ISSUE THREAD

**Issue by yakutovicha** [jupyterhub/mybinder.org-deploy#802]
Dear developers, would it be possible to open the port 22  for the outgoing ssh connections?
The reason why we are interested in that is the following:

As we are developing a tool for higg-throughput calculations called [AiiDA](https://github.com/aiidateam/aiida_core) we would like to provide for our potential users a possibility to try it before installing on their computers. Binder looks like a perfect platform for such tries. However, I am afraid that even if we run "very small calculations" directly on binder, our binder sessions will be considered as [Sessions that routinely use a large amount of CPU](https://mybinder.readthedocs.io/en/latest/user-guidelines.html#temporary-banning) and will eventually end up in your ban list. By "small calculations" I mean something that fully loads one CPU for 5-20 minutes.

Another possibility for us would be to run calculations on a remote test computer. However, to launch such a calculation AiiDA uses ssh connection, which is (according to my attempts to establish one) not allowed on mybinder.org. 

Being aware of possible security problems related to connections from public service (binder) to our private machine we will make sure to accept public keys only by request from trusted users. We will also be recreating the test machine with a certain frequency.

Thank you for your consideration.

**Comment by choldgraf** [comment]
Hey @yakutovicha - I suspect that we won't allow outgoing SSH connections less for security reasons and more for potential abuse reasons from others (e.g. we don't want somebody to use a Binder session to SSH into somebody's machine in a nefarious way and mess stuff up). Perhaps @yuvipanda or @betatim have thoughts on this?

That said (and assuming that outgoing SSH won't be enabled on `mybinder.org`), you've got a couple options:

1. Deploy your own BinderHub service. `mybinder.org` is just one instantiation of [BinderHub](https://binderhub.readthedocs.io/) which is an open project that can be deployed anywhere on Kubernetes. We restrict lots of stuff on `mybinder.org` because we run it as an anonymized, free service, but others who have deployed BinderHubs can set up their deployment however they like!
2. Restrict your Binder examples to a smaller size of data, set of computations, etc and make it clear how users would scale up if they worked locally. Often you don't need the kitchen sink just to get users interested in the tech. This is what a lot of scientific fields do when their data is on average too big to fit into memory.

I know those are both sub-optimal solutions, but let us know if you have any other thoughts or questions!

**Comment by yakutovicha** [comment]
Thanks @choldgraf and @betatim for your answers.

It is good to know that 15 minutes of CPU time is not a problem for mybinder. We will run our test calculations directly on the server then.

Repositories that I was referring two are: https://github.com/aiidalab/aiidalab-calculation-examples and  https://github.com/aiidateam/aiida_demos
