### ISSUE TITLE
Run mybinder.org on two clusters

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/mybinder.org-deploy#903]
Long term, we wanna run mybinder.org off multiple clusters in multiple locations hopefully fronted by different organizations. Like #759 

We can start off with having a second full cluster in the same project, while fulfilling the criteria @betatim set out in https://github.com/jupyterhub/mybinder.org-deploy/issues/759#issuecomment-464844791. This gives us a few advantages:

1. We have full control of the clusters
2. We can work out the technical issues present here
3. It makes our clusters more resilient, since we can continue to operate with one cluster down.

What do y'all think?

**Comment by yuvipanda** [comment]
I think steps for this would include:

1. Modify our deploy scripts to work with multiple clusters. One option here I'd like to explore is using [hubploy](http://github.com/yuvipanda/hubploy) - this is what we use at Berkeley for multiple hubs in multiple clusters in multiple projects, and PANGEO is using for multiple hubs in multiple clusters in multiple cloud providers!
2. Create a new cluster, and use this as an opportunity to switch to a regional cluster
3. Write something that can act as a load balancer between the two clusters, doing health checks & routing. This is a fairly generally solved problem with lots of solutions out there.

**Comment by betatim** [comment]
I like the idea of starting with a second cluster as part of our existing project on google cloud. We could probably start with a single machine cluster comparable to staging (keep costs down). Then route only traffic from users with a special cookie set (or something like that) to it.

Having hubploy would be nice in order to be able to retire `deploy.py`, though `deploy.py` has served us well (it gets changed rarely and has reached the point where it "just" works). Naively I see us making a copy of `config/prod.yaml` and `secrets/config/prod,yaml` for each extra cluster. Plus copying the last few lines of `.travis.yml` so that we run `deploy.py prod-us` and `deploy.py prod-fr` etc. What do you think in terms of how much more we'd need?

If the assumption on how much extra config/duplication/copy&paste there would be is right my priorities would be like this (given we have limited amounts of human time to work on this):
* get a second cluster deploying in parallel (accessible on some temporary name like foo.lb.mybinder.org)
* evaluate load balancer options
* implement one LB and expose it on some temp domain (lb.mybinder.org)
* implement a LB strategy based on a cookie people can set manually
* sit back and watch
* think about grafana, prometheus, analytics, event logging strategy
* start using hubploy for all hubs
* add a third cluster that is far away geographically (OVH?), start routing some traffic there

Likely by step three (or thereabouts) we will have changed our plan completely anyway so this is more about where to start.

---

I'd be super happy if we manage to organise the LB work so that it can be paused indefinitely when time/health/other commitments take priority. This means that I'd leave the current setup for mybinder.org "as is" for as long as possible. mybinder.org is running well right now and the amount of time needed for reactionary things continues to decrease which frees up time for doing other things (like this). If we start changing things I'd expect we need to spend more time in reactionary mode.

**Comment by betatim** [comment]
Did a bit of reading and research. Take away number one was that we want a HTTP redirector, not a HTTP proxy. Most examples in nginx, haproxy, etc concern themselves with load balancing in a way that that user can't tell. We want to actually redirect people.

nginx seems like it would require us to write some custom code (in C?) to implement clever health-checks (beyond HTTP status code based ones) or load balancing. not looked at HAproxy that closely.

I had a quick play with a Netlify redirector: https://github.com/betatim/geo-directions if you click the link in the repo description it will redirect you depending on your location. Config is in the repo. Nice how easy it is to do. Not powerful enough for us I think.

What about writing a small redirector based on Tornado? Feels like one of these "how hard can this be?" things that you regret down the road. Pro: we can do what ever we want in terms of load balancing, health checks, redirect policies. It would only see the initial requests and then 302 users somewhere. Wouldn't have to handle all traffic constantly (websockets, etc)

**Comment by yuvipanda** [comment]
Hmm, can't we use the text space to provide credit than a domain? If we use redirects, people will copy paste the URLs with the redirected domains. This makes it harder to have them come and go...

IMO we should differentiate multiple clusters hosting my binder.org from federation. The former should have a consistent domain name and centralized deployment, and the latter should have redirects and distributed control.

**Comment by betatim** [comment]
(
Defining some terms to help keep my sentences consistent:
* a cluster == a kubernetes cluster
* a deployment might consist of one or more clusters
* a federation consists of two or more deployments
)

I had assumed that this issue was about setting up two deployments (using the above definitions) so that we could form a federation (with ourselves).

I agree that multiple clusters that form one deployment should be handled transparently. Also that the different deployments that form a federation should be reachable via redirects/explicit hostnames.

I think the deployments in a federation should still be centrally managed as that seems like the best story we have for keeping them in step in terms of deployed versions of software.

Even for the federation I think improving how people get the link to share is on our todo list. You'd want people to share a link that is independent of the particular deployment they ended up on. For exactly the reasons you mentioned. IMHO the fix is to deploy the sharing buttons GESIS uses.

**Comment by SylvainCorlay** [comment]
Hey all, I have created a doodle poll to set up a time for a hands-on discussion with the OVH team on what could be the next steps

https://doodle.com/poll/88e4vxkw4epikn7r

cc @choldgraf @yuvipanda @betatim @willingc

**Comment by SylvainCorlay** [comment]
(Sorry for cross-posting.)

**Comment by yuvipanda** [comment]
Federation is <3 now, and we run on many clusters!
