### ISSUE TITLE
Increasing Number of Simultaneous Users

### ISSUE THREAD

**Issue by jason2249** [jupyterhub/mybinder.org-deploy#905]
Hi all,

I'm currently TAing an [introductory programming class](https://web.stanford.edu/class/cs106ap/), and the lecturer has expressed interest in doing a lecture on Jupyter Notebooks. We would basically just be showing off the features of a Jupyter Notebook with a single .ipynb file and there would be little computation involved (probably something like drawing simple graphs). 

I came across binder, and it seems like a really great tool to use for the lecture and/or a single homework assignment/discussion section. We wanted to avoid having students download jupyter themselves, as they're all novice students who haven't worked with the command line at all before, and previous attempts at doing so have been pretty rough. However, I noticed that the [binder usage guidelines](https://mybinder.readthedocs.io/en/latest/user-guidelines.html#maximum-concurrent-users-for-a-repository) state that a maximum of 100 users may be on a repository at a single time. Our class has 205 students enrolled, so if we wanted students to interactively follow along during lecture, this wouldn't be able to work. 

Would it be possible to increase the limit to 200 for certain repositories for this class? I don't have the repositories up yet, but I'm just wondering if using binder would be a possibility at all. If not, are there any other alternative services you would recommend for this? 

Thanks!

**Comment by betatim** [comment]
Hi 👋 !

I think Binder would be exactly the right tool for this. We currently can only set the "maximum concurrent users per repo" on a global level/for all of mybinder.org. It is set to 100 because that seems to hardly ever come into effect and when it does come into effect it limits our most popular repository only. This means that we haven't seen legitimate repositories run into this limit. What it does do is protect us from very large hosting bills due to accidental "run away repos" and malicious users.

There are a few options for using mybinder.org for you:
1. make two repositories `myuniversity/jupyter-101-a` and `myuniversity/jupyter-101-b`, half the students use one and the other half the other. This is what someone from Microsoft ended up doing for a live demo to an audience of ~150
1. help us get pre-repo-limits added to BinderHub. This would be my favourite option
1. run your own JupyterHub for the day

Having a per repo limit has been on the wish list for a while but no one has gotten around to building it yet. It seems like helping you add this would be a win-win. The Binder community gest a new feature and you get to use mybinder.org. I also like it because the time and effort spent on it would be generally useful so it is more of an investment than a cost.

Overall it would be great to work with you on this. No matter whether you choose 1 or 2 from above it would be good if we can coordinate a bit when your class will be. While the cluster behind mybinder.org scales up automatically, the scale up take about 8minutes. We don't run the cluster with enough headroom for 200 students to arrive all within a minute or two. So we'd want to make some custom arrangements for your demo either way to make sure you have a great demo experience.

**Comment by jason2249** [comment]
Hi Tim,

Thanks for the info! Unfortunately I'm swamped with school work at the moment and the lecture will be this Friday at 1:30-2:20PM PST, so I won't be able to help you guys get the per repo limits added. I think option 1, using 2 repos, sounds like a great idea! 

Let me run this through with the lecturer tomorrow - I will let you know what he thinks and if we'll be going through with the demo on Friday. With the custom arrangements, would the scale up time be shorter?

**Comment by betatim** [comment]
I'd propose that we try and trigger a scale up just before the lecture as a way to smooth out the load.

It does require someone to have some spare time to work on this, try it out, and be available around when your lecture is. Everyone who works on mybinder.org volunteers their time so it requires some lobbying from your side to find out who has time etc. I'd stop by https://gitter.im/jupyterhub/binder to start a discussion in that direction.

For me 1pm PST on a Friday is pretty late/deep into the weekend :-/

**Comment by jason2249** [comment]
Ah I see. A possible alternative would be to just demo the notebook during lecture on the projector instead of having everyone do it, and then distribute a homework assignment through binder? It'd be very unlikely that all students join the instance at the same time in that case, so I don't think we'd need to worry as much about scaling issues. Also, are there any issues with splitting up a repo into 3 pieces, just to avoid the possibility of hitting 100 concurrent users?

**Comment by jason2249** [comment]
OK, we'll probably go ahead with a single demo in front of the class as opposed to all 200 students using it to avoid any possible headaches. For using binder with homework, it seems like all changes to a binder instance are thrown away once your session goes inactive, which wouldn't be ideal with a homework assignment, as students may want to work a bit then come back later and have everything saved. Do you know of any way of saving work done in binder?

**Comment by betatim** [comment]
> Do you know of any way of saving work done in binder?

https://mybinder.readthedocs.io/en/latest/faq.html#can-i-push-data-from-my-binder-session-back-to-my-repository

I'd download your work and handle submission via some other method. We recommend against people typing secrets (like passwords and GitHub account details) into session on mybinder.org.

**Comment by jason2249** [comment]
Gotcha. Thank you a ton for your help!
