### ISSUE TITLE
R shiny with package installed from github

### ISSUE THREAD

**Issue by Athanasiamo** [jupyterhub/mybinder.org-deploy#907]
Hi. Is there any way to install a package from github in a binderhub shiny app deploy?

I've tried adding `devtools::install_github()` in the `install.R` file, (after devtools install ofc), but that does not seem to do it? At least the build is failing.

**Comment by choldgraf** [comment]
hey! 👋 that's a good question, I think the best place would probably be in the [repo2docker issues](https://github.com/jupyter/repo2docker/issues), since that's what is handling the R installation steps. Would you mind opening one up there? The mybinder.org-deploy repository is specific to `mybinder.org` but this sounds like a more generic problem for repo2docker!

(also, it would be helpful if you can add a link to your github repository, and/or the error message you're getting)

**Comment by betatim** [comment]
Do we have someone with the appropriate admin privileges to move the issue?

---

I will reply here hoping we will get moved, otherwise I'll repeat it in the new issue.

The lines in `install.R` get [run as an Rscript](https://github.com/jupyter/repo2docker/blob/b3a642ba5096ee1882f5b32f7e28853a398431b2/repo2docker/buildpacks/r.py#L295-L299) (I think that is the right terminology) so in principle you should be able to use `devtools::install_github()` there. We also use it to [install other things for you](https://github.com/jupyter/repo2docker/blob/b3a642ba5096ee1882f5b32f7e28853a398431b2/repo2docker/buildpacks/r.py#L253). So this should work :-/ Maybe a link to the repository is indeed the next step.

**Comment by choldgraf** [comment]
@betatim I tried that but we can't move issues between organizations, and repo2docker is a jupyter org project, not a jupyterhub one

**Comment by betatim** [comment]
Closed this issue and linked the new one in the repo2docker repository.
