### ISSUE TITLE
Redirect small number of users to staging

### ISSUE THREAD

**Issue by betatim** [jupyterhub/mybinder.org-deploy#94]
Can we redirect a small percentage of users to staging (without them noticing) in some kind of A/B testing like setup? The purpose of this would be to be able to look at failure rates to detect when a change has been deployed to staging that breaks something.

**Comment by yuvipanda** [comment]
While I agree this would be a useful thing to have,

1. We must make sure that we don't knowlingly send users to a setup that we *know* will fail (because automated tests fail, for example)
2. This is useful at high rates of request, where a failure is easily fixable (user just hits refresh). We don't have that volume yet, so we shouldn't do this until we do.
3. We should be very clear on what we are looking to test. For example, with #83, these two would be entirely different clusters, and staging would be much smaller. So it might fail just due to capacity issues, for example.

It's a good idea that we should carefully prioritize and decide what we want to get out of it before we implement. My personal feeling is that we've a while to go before this is useful to us.

**Comment by yuvipanda** [comment]
I'm going to close this for now, until IMO we're large enough for this kinda deployment to be useful to us. Is that ok with you, @betatim?
